name: pull request
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
      - name: Install Requirements
        run:
          pip install -r requirements.txt
      - name: Pylint
        run:
          pylint circuit_breaker_validator/
      - name: Black
        run:
          black --check ./
      - name: Type Check (mypy)
        run: mypy circuit_breaker_validator --strict
      - name: Unit Tests
        run:
          python -m pytest tests/
